[package]
name = "lemon"
version = "0.1.0"
authors = ["Aidan Heller <asfheller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11.0-rc5"
rustyline = "6.1"
